import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import './globals.css'

const league_Spartan = League_Spartan({
  weight: ['500','700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={league_Spartan.className}>{children}</body>
    </html>
  )
}
